#!/bin/bash

# This script processes a SINGLE metagenomic sample from an INTERLEAVED FASTQ file.
# It performs read mapping (Bowtie2) and inStrain profiling.
# It is designed to be called by GNU Parallel.

set -e
set -x

# --- 1. SCRIPT ARGUMENTS ---
readonly SAMPLE_NAME=$1
if [ -z "$SAMPLE_NAME" ]; then
    echo "Error: Sample name not provided."
    exit 1
fi

# --- 2. CONFIGURATION ---
readonly CONDA_ENV_NAME="instrain"
# Directory for your interleaved reads (e.g., sample1.clean.fastq.gz)
readonly READS_DIR="/home/wulab/project/new_warming/hq_reads"
readonly OUTPUT_DIR="/home/linwei/nws0920/19_instrain/selection_analysis_v2"
# Threads for a single bowtie2/inStrain job
readonly THREADS_PER_JOB=4

# --- Reference File Paths (generated by prepare_references.sh) ---
readonly ALL_MAGS_FA="$OUTPUT_DIR/all_mags_reference.fasta"
readonly BT2_INDEX="$OUTPUT_DIR/bowtie2_index/all_mags_bt2"
readonly STB_FILE="$OUTPUT_DIR/scaffold_to_bin.tsv"
readonly ALL_GENES_FNA="$OUTPUT_DIR/all_mags.genes.fna"

# --- Activate Conda Environment ---

# --- 3. DEFINE PATHS FOR THIS SAMPLE (MODIFIED FOR INTERLEAVED READS) ---
# The input read file now has the .clean.fastq.gz suffix
readonly READ_FILE="$READS_DIR/${SAMPLE_NAME}.clean.fastq.gz"
readonly SAM_FILE="$OUTPUT_DIR/01_mappings/${SAMPLE_NAME}.sam"
readonly PROFILE_DIR="$OUTPUT_DIR/02_instrain_profiles/${SAMPLE_NAME}"

# Check if the input read file exists
if [ ! -f "$READ_FILE" ]; then
    echo "Error: Read file for sample $SAMPLE_NAME not found at $READ_FILE"
    exit 1
fi

# --- 4. RUN PIPELINE FOR THE SAMPLE ---
echo "--- Processing sample: $SAMPLE_NAME ---"

# Check if final output exists, if so, skip
if [ -d "$PROFILE_DIR" ]; then
    echo "Profile for $SAMPLE_NAME already exists. Skipping."
    exit 0
fi

mkdir -p "$OUTPUT_DIR/01_mappings"

# Step 4.1: Mapping with Bowtie2 (MODIFIED FOR INTERLEAVED READS)
echo "  [1/2] Mapping interleaved reads for $SAMPLE_NAME with Bowtie2..."
echo "Using read file: $READ_FILE"
bowtie2 -p "$THREADS_PER_JOB" \
        -x "$BT2_INDEX" \
        --interleaved "$READ_FILE" \
        -S "$SAM_FILE" \
        --no-unal

# Step 4.2: inStrain Profiling from SAM file (This part remains the same)
echo "  [2/2] Running inStrain profile for $SAMPLE_NAME..."
inStrain profile "$SAM_FILE" "$ALL_MAGS_FA" \
    -o "$PROFILE_DIR" \
    -s "$STB_FILE" \
    -g "$ALL_GENES_FNA" \
    -p "$THREADS_PER_JOB" \
    --database_mode

# Step 4.3: Cleanup
rm "$SAM_FILE"

echo "--- Finished processing sample: $SAMPLE_NAME ---"
